docker run --rm \
  -v ${PWD}:/local openapitools/openapi-generator-cli generate \
  -i /local/openapi.yaml  \
  -g php \
  -o /local/ \
  --git-user-id rvvup \
  --git-repo-id rvvup-php-openapi \
  --invoker-package=Rvvup \
  --api-package=Api \
  --model-package=Api\\Model
  --additional-properties=composerPackageName=rvvup/php-openapi,developerOrganization=Rvvup,developerOrganizationUrl=https://rvvup.com,licenseName=MIT,packageName=Rvvup/Api