<?php
/**
 * CheckoutTemplateUpdateInput
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Rvvup
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rvvup API
 *
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Rvvup\Api\Model;

use \ArrayAccess;
use \Rvvup\ObjectSerializer;

/**
 * CheckoutTemplateUpdateInput Class Doc Comment
 *
 * @category Class
 * @description The input for updating a checkout template.
 * @package  Rvvup
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CheckoutTemplateUpdateInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CheckoutTemplateUpdateInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'amount_type' => '\Rvvup\Api\Model\CheckoutAmountType',
        'customer_fields' => '\Rvvup\Api\Model\CheckoutCustomerFieldsUpdateInput',
        'disabled_payment_methods' => '\Rvvup\Api\Model\PaymentMethod[]',
        'enabled_payment_methods' => '\Rvvup\Api\Model\PaymentMethod[]',
        'name' => 'string',
        'notify_customer' => 'bool',
        'notify_merchant' => 'bool',
        'payment_method_settings' => '\Rvvup\Api\Model\CheckoutPaymentMethodSettingsUpdateInput',
        'reference_type' => '\Rvvup\Api\Model\CheckoutReferenceType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'amount_type' => null,
        'customer_fields' => null,
        'disabled_payment_methods' => null,
        'enabled_payment_methods' => null,
        'name' => null,
        'notify_customer' => null,
        'notify_merchant' => null,
        'payment_method_settings' => null,
        'reference_type' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'amount_type' => false,
        'customer_fields' => false,
        'disabled_payment_methods' => false,
        'enabled_payment_methods' => false,
        'name' => false,
        'notify_customer' => false,
        'notify_merchant' => false,
        'payment_method_settings' => false,
        'reference_type' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'amount_type' => 'amountType',
        'customer_fields' => 'customerFields',
        'disabled_payment_methods' => 'disabledPaymentMethods',
        'enabled_payment_methods' => 'enabledPaymentMethods',
        'name' => 'name',
        'notify_customer' => 'notifyCustomer',
        'notify_merchant' => 'notifyMerchant',
        'payment_method_settings' => 'paymentMethodSettings',
        'reference_type' => 'referenceType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'amount_type' => 'setAmountType',
        'customer_fields' => 'setCustomerFields',
        'disabled_payment_methods' => 'setDisabledPaymentMethods',
        'enabled_payment_methods' => 'setEnabledPaymentMethods',
        'name' => 'setName',
        'notify_customer' => 'setNotifyCustomer',
        'notify_merchant' => 'setNotifyMerchant',
        'payment_method_settings' => 'setPaymentMethodSettings',
        'reference_type' => 'setReferenceType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'amount_type' => 'getAmountType',
        'customer_fields' => 'getCustomerFields',
        'disabled_payment_methods' => 'getDisabledPaymentMethods',
        'enabled_payment_methods' => 'getEnabledPaymentMethods',
        'name' => 'getName',
        'notify_customer' => 'getNotifyCustomer',
        'notify_merchant' => 'getNotifyMerchant',
        'payment_method_settings' => 'getPaymentMethodSettings',
        'reference_type' => 'getReferenceType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDisabledPaymentMethodsAllowableValues()
    {
        return [
            
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEnabledPaymentMethodsAllowableValues()
    {
        return [
            
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('amount_type', $data ?? [], null);
        $this->setIfExists('customer_fields', $data ?? [], null);
        $this->setIfExists('disabled_payment_methods', $data ?? [], null);
        $this->setIfExists('enabled_payment_methods', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('notify_customer', $data ?? [], false);
        $this->setIfExists('notify_merchant', $data ?? [], false);
        $this->setIfExists('payment_method_settings', $data ?? [], null);
        $this->setIfExists('reference_type', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['name']) && (mb_strlen($this->container['name']) > 255)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['name']) && (mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amount_type
     *
     * @return \Rvvup\Api\Model\CheckoutAmountType|null
     */
    public function getAmountType()
    {
        return $this->container['amount_type'];
    }

    /**
     * Sets amount_type
     *
     * @param \Rvvup\Api\Model\CheckoutAmountType|string|null $amount_type amount_type
     *
     * @return self
     */
    public function setAmountType($amount_type)
    {
        if (is_null($amount_type)) {
            throw new \InvalidArgumentException('non-nullable amount_type cannot be null');
        }
        $this->container['amount_type'] = $amount_type;

        return $this;
    }

    /**
     * Gets customer_fields
     *
     * @return \Rvvup\Api\Model\CheckoutCustomerFieldsUpdateInput|null
     */
    public function getCustomerFields()
    {
        return $this->container['customer_fields'];
    }

    /**
     * Sets customer_fields
     *
     * @param \Rvvup\Api\Model\CheckoutCustomerFieldsUpdateInput|null $customer_fields customer_fields
     *
     * @return self
     */
    public function setCustomerFields($customer_fields)
    {
        if (is_null($customer_fields)) {
            throw new \InvalidArgumentException('non-nullable customer_fields cannot be null');
        }
        $this->container['customer_fields'] = $customer_fields;

        return $this;
    }

    /**
     * Gets disabled_payment_methods
     *
     * @return \Rvvup\Api\Model\PaymentMethod[]|null
     */
    public function getDisabledPaymentMethods()
    {
        return $this->container['disabled_payment_methods'];
    }

    /**
     * Sets disabled_payment_methods
     *
     * @param \Rvvup\Api\Model\PaymentMethod[]|null $disabled_payment_methods The set of payment methods that are disabled for the checkout.
     *
     * @return self
     */
    public function setDisabledPaymentMethods($disabled_payment_methods)
    {
        if (is_null($disabled_payment_methods)) {
            throw new \InvalidArgumentException('non-nullable disabled_payment_methods cannot be null');
        }
        $allowedValues = $this->getDisabledPaymentMethodsAllowableValues();
        if (array_diff($disabled_payment_methods, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'disabled_payment_methods', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }


        $this->container['disabled_payment_methods'] = $disabled_payment_methods;

        return $this;
    }

    /**
     * Gets enabled_payment_methods
     *
     * @return \Rvvup\Api\Model\PaymentMethod[]|null
     */
    public function getEnabledPaymentMethods()
    {
        return $this->container['enabled_payment_methods'];
    }

    /**
     * Sets enabled_payment_methods
     *
     * @param \Rvvup\Api\Model\PaymentMethod[]|null $enabled_payment_methods Ordered list of payment methods that are enabled for the checkout. An empty list means all payment methods are enabled.
     *
     * @return self
     */
    public function setEnabledPaymentMethods($enabled_payment_methods)
    {
        if (is_null($enabled_payment_methods)) {
            throw new \InvalidArgumentException('non-nullable enabled_payment_methods cannot be null');
        }
        $allowedValues = $this->getEnabledPaymentMethodsAllowableValues();
        if (array_diff($enabled_payment_methods, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'enabled_payment_methods', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['enabled_payment_methods'] = $enabled_payment_methods;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The name of the checkout template.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $name when calling CheckoutTemplateUpdateInput., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling CheckoutTemplateUpdateInput., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets notify_customer
     *
     * @return bool|null
     */
    public function getNotifyCustomer()
    {
        return $this->container['notify_customer'];
    }

    /**
     * Sets notify_customer
     *
     * @param bool|null $notify_customer Whether the customer should be notified on payment completion.
     *
     * @return self
     */
    public function setNotifyCustomer($notify_customer)
    {
        if (is_null($notify_customer)) {
            throw new \InvalidArgumentException('non-nullable notify_customer cannot be null');
        }
        $this->container['notify_customer'] = $notify_customer;

        return $this;
    }

    /**
     * Gets notify_merchant
     *
     * @return bool|null
     */
    public function getNotifyMerchant()
    {
        return $this->container['notify_merchant'];
    }

    /**
     * Sets notify_merchant
     *
     * @param bool|null $notify_merchant Whether you should be notified on payment completion.
     *
     * @return self
     */
    public function setNotifyMerchant($notify_merchant)
    {
        if (is_null($notify_merchant)) {
            throw new \InvalidArgumentException('non-nullable notify_merchant cannot be null');
        }
        $this->container['notify_merchant'] = $notify_merchant;

        return $this;
    }

    /**
     * Gets payment_method_settings
     *
     * @return \Rvvup\Api\Model\CheckoutPaymentMethodSettingsUpdateInput|null
     */
    public function getPaymentMethodSettings()
    {
        return $this->container['payment_method_settings'];
    }

    /**
     * Sets payment_method_settings
     *
     * @param \Rvvup\Api\Model\CheckoutPaymentMethodSettingsUpdateInput|null $payment_method_settings payment_method_settings
     *
     * @return self
     */
    public function setPaymentMethodSettings($payment_method_settings)
    {
        if (is_null($payment_method_settings)) {
            throw new \InvalidArgumentException('non-nullable payment_method_settings cannot be null');
        }
        $this->container['payment_method_settings'] = $payment_method_settings;

        return $this;
    }

    /**
     * Gets reference_type
     *
     * @return \Rvvup\Api\Model\CheckoutReferenceType|null
     */
    public function getReferenceType()
    {
        return $this->container['reference_type'];
    }

    /**
     * Sets reference_type
     *
     * @param \Rvvup\Api\Model\CheckoutReferenceType|string|null $reference_type reference_type
     *
     * @return self
     */
    public function setReferenceType($reference_type)
    {
        if (is_null($reference_type)) {
            throw new \InvalidArgumentException('non-nullable reference_type cannot be null');
        }
        $this->container['reference_type'] = $reference_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


