<?php
/**
 * ConnectionStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Rvvup
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zopa Payments API
 *
 * Zopa Payments Public API, previously the Rvvup API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: merchantsupport@zopa.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Rvvup\Api\Model;
use \Rvvup\ObjectSerializer;

/**
 * ConnectionStatus Class Doc Comment
 *
 * @category Class
 * @description The connection status.
 * @package  Rvvup
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConnectionStatus
{
    /**
     * Possible values of this enum
     */
    public const CONNECTED = 'CONNECTED';

    public const DISCONNECTED = 'DISCONNECTED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CONNECTED,
            self::DISCONNECTED
        ];
    }
}


