<?php
/**
 * WebhookEventType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Rvvup
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zopa Payments API
 *
 * Zopa Payments Public API, previously the Rvvup API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: merchantsupport@zopa.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Rvvup\Api\Model;
use \Rvvup\ObjectSerializer;

/**
 * WebhookEventType Class Doc Comment
 *
 * @category Class
 * @description The event type of the webhook.
 * @package  Rvvup
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhookEventType
{
    /**
     * Possible values of this enum
     */
    public const PAYMENT_AUTHORIZED = 'PAYMENT_AUTHORIZED';

    public const PAYMENT_COMPLETED = 'PAYMENT_COMPLETED';

    public const PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED';

    public const REFUND_COMPLETED = 'REFUND_COMPLETED';

    public const REFUND_SUCCEEDED = 'REFUND_SUCCEEDED';

    public const PAYMENT_LINK_EXPIRED = 'PAYMENT_LINK_EXPIRED';

    public const DISBURSEMENT_FINALIZED = 'DISBURSEMENT_FINALIZED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PAYMENT_AUTHORIZED,
            self::PAYMENT_COMPLETED,
            self::PAYMENT_SUCCEEDED,
            self::REFUND_COMPLETED,
            self::REFUND_SUCCEEDED,
            self::PAYMENT_LINK_EXPIRED,
            self::DISBURSEMENT_FINALIZED
        ];
    }
}


