<?php
/**
 * ZopaRetailFinanceIncomeType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Rvvup
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zopa Payments API
 *
 * Zopa Payments Public API, previously the Rvvup API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: merchantsupport@zopa.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Rvvup\Api\Model;
use \Rvvup\ObjectSerializer;

/**
 * ZopaRetailFinanceIncomeType Class Doc Comment
 *
 * @category Class
 * @package  Rvvup
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ZopaRetailFinanceIncomeType
{
    /**
     * Possible values of this enum
     */
    public const EMPLOYED_FULL_TIME = 'EMPLOYED_FULL_TIME';

    public const EMPLOYED_PART_TIME = 'EMPLOYED_PART_TIME';

    public const SELF_EMPLOYED = 'SELF_EMPLOYED';

    public const PENSION = 'PENSION';

    public const OTHER = 'OTHER';

    public const DIRECTOR_LIMITED_COMPANY = 'DIRECTOR_LIMITED_COMPANY';

    public const UNEMPLOYED = 'UNEMPLOYED';

    public const RETIRED = 'RETIRED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EMPLOYED_FULL_TIME,
            self::EMPLOYED_PART_TIME,
            self::SELF_EMPLOYED,
            self::PENSION,
            self::OTHER,
            self::DIRECTOR_LIMITED_COMPANY,
            self::UNEMPLOYED,
            self::RETIRED
        ];
    }
}


