<?php
/**
 * AccountStatementPaymentPreviewInputTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Rvvup
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zopa Payments API
 *
 * Zopa Payments Public API, previously the Rvvup API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: merchantsupport@zopa.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Rvvup\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AccountStatementPaymentPreviewInputTest Class Doc Comment
 *
 * @category    Class
 * @description Input for computing a payment preview with credit note application.
 * @package     Rvvup
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AccountStatementPaymentPreviewInputTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AccountStatementPaymentPreviewInput"
     */
    public function testAccountStatementPaymentPreviewInput()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "credit_note_ids"
     */
    public function testPropertyCreditNoteIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "invoice_ids"
     */
    public function testPropertyInvoiceIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
