<?php
/**
 * ShipmentTrackingApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Rvvup
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rvvup API
 *
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Rvvup\Test\Api;

use \Rvvup\Configuration;
use \Rvvup\ApiException;
use \Rvvup\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ShipmentTrackingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rvvup
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShipmentTrackingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createShipmentTracking
     *
     * Create a shipment tracking entry for a payment session.
     *
     */
    public function testCreateShipmentTracking()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createShipmentTrackingWithCheckout
     *
     * Create a shipment tracking entry for a payment session.
     *
     */
    public function testCreateShipmentTrackingWithCheckout()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
